### ISSUE TITLE
labels mapping with explain_prediction

### ISSUE THREAD

**Issue by GS756** [MarcelRobeer/explabox#10]
[//]: # (What is the bug that you encountered?)
## Summary of bug
When using `box.explain.explain_prediction(input_text)`, there sometimes is a confusion between the classes and their labels. in these cases, all the scores are correct, but not the name associated with each class, even though a correct mapping dictionnary was provided as `label_map` when declaring `data` and `model`.

[//]: # (Which OS, Python version and Explabox version did you encounter this bug in?)
## Environment information
- Platform: Windows 11
- *Python* version: 3.10.4
- `explabox` version: ?

[//]: # (How can we reproduce the bug? Note that this information is available publicly within the HaaS git, feel free to anonymize any irrelevant information, such as user IDs and/or names)
## Reproducing the bug
- with any dataset with >2 classes, shaped as two dataframes `df_train` and `df_test`, with `text` and `label` columns, 
- apply all desired cleaning and vectorizing steps within a classifier here called `pipe`, 
- provide a dictionnary `labels_dict = {0: name_class_0, ...}`
- choose any sample `input_text =  "your text here about class 0 but not about class 3"`
- and use the following code:

```python
from explabox import Explabox
from explabox import import_data
from explabox import import_model

data = import_data({'train': df_train, 'test': df_test}, data_cols='text', label_cols='label', 
                   label_map=labels_dict)
model = import_model(pipe, data, label_map=labels_dict)

box = Explabox(data=data,
               model=model,
               splits={'train': 'train', 'test': 'test'})

print(pipe.predict([input_text])) # to check what class the prediction gives
print(pipe.predict_proba([input_text])) # to check the scores
box.explain.explain_prediction(input_text)
```

[//]: # (What did you try to fix the problem yourself?)
## Solutions Attempted
The problem is not reproductible, it sometimes happen, sometimes not, on the same data. I tried re-declaring the mapping dictionnary and checking it was correct, but it always was when the problem occurred.

**Comment by MarcelRobeer** [comment]
Thank you @GS756 for reporting the bugs! Would you be so kind to split the bugs into two issue reports; one for the first bug and one for the second? I will look into them ASAP.
