### ISSUE TITLE
Cannot pickle generator object

### ISSUE THREAD

**Issue by riwish** [MarcelRobeer/explabox#2]
[//]: # (What is the bug that you encountered?)
## Summary of bug
The `explain_prediction` method behaves differently for tokens with a length greater than size 8. 

The error message is: 
`TypeError: cannot pickle 'generator' object`

The error is found in: `text_eplainability > generation > return_types.py` at lline 195
`self._neighborhood_instances = copy.deepcopy(self._provider.get_children(self._original_instance))`

[//]: # (Which OS, Python version and Explabox version did you encounter this bug in?)
## Environment information
- Platform: OS independent
- *Python* version: 3.9
- `explabox` version: 0.9b4

[//]: # (How can we reproduce the bug? Note that this information is available publicly within the HaaS git, feel free to anonymize any irrelevant information, such as user IDs and/or names)
## Reproducing the bug
This bug happens to appear for multiple cases. The easiest way to reproduce is to follow the demo-drug dataset steps and use a sentence with 8 or more words in the explain section.

[//]: # (What did you try to fix the problem yourself?)
## Solutions Attempted
The error seems to be gone by removing the copy:
`self._neighborhood_instances = self._provider.get_children(self._original_instance)`

[//]: # (What did you expect to happen instead?)
## Expected behavior
Output widget

**Comment by MarcelRobeer** [comment]
My suggestion would be to prevent direct usage of `copy.deepcopy(...)` throughout the `explabox`, but rather make a new feature enhancement in `genbase` that allows for a `safe_deepcopy(...)` function that checks if objects can be pickled, and if not transforms them into a format that allows pickling.

**Comment by MarcelRobeer** [comment]
Solution presented above was not needed, because it was not the overall sequence that was a generator but one subpart thereof. This subpart (the new untokenized string) should have been a sequence anyway, so we fixed that in `text_explainability==0.6.4`.
