### ISSUE TITLE
Drugsreview notebook doesn't work properly due to specific pandas package version

### ISSUE THREAD

**Issue by riwish** [MarcelRobeer/explabox#5]
[//]: # (What is the bug that you encountered?)
## Summary of bug
The drugsreview dataset throws an error during the processing of ingestibles. The error being thrown is 
`module 'pandas.io.common' has no attribute '_compression_to_extension'`

[//]: # (Which OS, Python version and Explabox version did you encounter this bug in?)
## Environment information
- Platform: MacOs
- *Python* version: 3.9.0
- `explabox` version: 0.9b7

[//]: # (How can we reproduce the bug? Note that this information is available publicly within the HaaS git, feel free to anonymize any irrelevant information, such as user IDs and/or names)
## Reproducing the bug

Run the first couple of cells of the current explabox durgsreview demo notebook, section '1. Ingestibles'

```python
from explabox import import_data
data = import_data(dataset_file, data_cols='review', label_cols='rating')
...
```

[//]: # (What did you try to fix the problem yourself?)
## Solutions Attempted
I Googled the exception and saw it may be caused due to relying on a specific pandas version. I tried downgrading pandas `1.5.3` to `1.4.0` and the error was gone.

[//]: # (What did you expect to happen instead?)
## Expected behavior
A successfully completed Jupyter Notebook Cell without errors

**Comment by MarcelRobeer** [comment]
This indeed seems to be because of a update of `pandas` (`pd`) versions, where in `pandas.io.common` the dictionary `_compression_to_extension` has been changed over to `extension_to_compression`. The issue comes from dependency `genbase`, which I will update.

**Change in `genbase.data.__init__`**:
```python
...
if file_type in pd.io.common._compression_to_extension.values():
    ...
```
to
```python
...
extensions = pd.io.common._compression_to_extension.values() \
    if hasattr(pd.io.common, '_compression_to_extension') \
    else pd.io.common.extension_to_compression.keys()
if file_type in extensions:
    ...
```
