### ISSUE TITLE
Drugsreview notebook doesn't work properly due to specific transformers package version

### ISSUE THREAD

**Issue by riwish** [MarcelRobeer/explabox#6]
[//]: # (What is the bug that you encountered?)
## Summary of bug
The drugsreview dataset throws an error during the examine function. The error being thrown is 
`AttributeError: 'BertTokenizerFast' object has no attribute '_in_target_context_manager'`

[//]: # (Which OS, Python version and Explabox version did you encounter this bug in?)
## Environment information
- Platform: MacOs
- *Python* version: 3.9.0
- `explabox` version: 0.9b7

[//]: # (How can we reproduce the bug? Note that this information is available publicly within the HaaS git, feel free to anonymize any irrelevant information, such as user IDs and/or names)
## Reproducing the bug

Run the first couple of cells of the current explabox durgsreview demo notebook, section '3. Examine'

```python
...
from explabox import Explabox

box = Explabox(data=data,
               model=model,
               splits={'train': 'drugsComTrain.tsv', 'test': 'drugsComTest.tsv'})
box.examine()
...
```

[//]: # (What did you try to fix the problem yourself?)
## Solutions Attempted
I Googled the exception and saw it may be caused due to relying on a specific transformers version. I tried downgrading transformers `4.25.1` to `4.20.1` and the error was gone.

[//]: # (What did you expect to happen instead?)
## Expected behavior
A digestable displayed in the form of a widget in my jupyter notebook.

**Comment by MarcelRobeer** [comment]
Bug was due to incompatibility of an old `tokenizer` version with the new `tokenizer` in `transformers==4.25.1`. The bug is now patched in `explabox-demo-drugreview==0.9b12` (by default it tries to use the online tokenizer on the `huggingface` model page, and if using that fails `tokenizer.pkl` is used as a back-up).
