### ISSUE TITLE
Drugsreview notebook prints lots of linebreaks at section 5.1

### ISSUE THREAD

**Issue by riwish** [MarcelRobeer/explabox#7]
[//]: # (What is the bug that you encountered?)
## Summary of bug
The explabox drugsreview notebook prints lots of linebreaks `</>` at section 5.1

[//]: # (Which OS, Python version and Explabox version did you encounter this bug in?)
## Environment information
- Platform: MacOs
- *Python* version: 3.9
- `explabox` version: 0.9b7

[//]: # (How can we reproduce the bug? Note that this information is available publicly within the HaaS git, feel free to anonymize any irrelevant information, such as user IDs and/or names)
## Reproducing the bug

Run the explabox review notebook until section 5.1

```python
...
box.expose.input_space('all', min_length=0, max_length=6000)
```

[//]: # (What did you try to fix the problem yourself?)
## Solutions Attempted
I didn't try to fix the problem as I haven't found the issue problematic. The desired output was being shown, however I was confused by the many linebreaks (>10) and wanted to report this unexpected behaviour.

[//]: # (What did you expect to happen instead?)
## Expected behavior
A digestable type of output but without preceding linebreaks

**Comment by MarcelRobeer** [comment]
Have discussed this with @mpbron. We require a patch in dependency [`instancelib-onnx`](https://github.com/mpbron/instancelib-onnx) to fix this behavior. Once the feature has been added to disable `tqdm` output in `instancelib-onnx` we will fix in in the `explabox`.

**Comment by MarcelRobeer** [comment]
I have found and alternate fix, where `tqdm` is silenced in general in an imported package. This behavior is fixed by silencing `tqdm` in `instancelib.machinelearning`, through adding the

```python
import instancelib.machinelearning
from genbase import silence_tqdm

with silence_tqdm(instancelib.machinelearning):
    for i in instances:
        ...
```

statement in `text_sensitivity.input_space_robustness()`. The outer for-loop does contain `tqdm` to show a progress bar.
