### ISSUE TITLE
High-level visual overview of the dataset

### ISSUE THREAD

**Issue by riwish** [MarcelRobeer/explabox#9]
[//]: # (What is your suggestion?)
## Feature suggestion
When working with new data(sets) one might need more visuals than the current `explore()` functions. One suggestion in particular would be to see and investigate the actual data, just like `pandas.head()`. 

[//]: # (What is the purpose of the new feature? Why would you like to have it?)
## Purpose/Goal
I can imagine that adding the abovementioned feature could really help in getting a better global idea of the data which in turn makes it easier to know which type of explabox functions to apply later on.

[//]: # (What would you imagine working with the final product to be like?)
## Usage example
I can think of two scenario's in which this suggestion could be implemented. Either incorporate a visual of the first row and columns in the digestible of `box.explore()` or add a subfunction to explore which can be accessed like `box.explore.head()`. Even though both provided solutions may work, I have to mention that the first implementation seems to be more favorable.

**Comment by MarcelRobeer** [comment]
Thank you for your suggestion! I have added a `Dataset` digestibles (which can be accessed through `box.explore.instances()`), where you can see all instances in a split (with their ground-truth labels) and where you can select, sample and filter instances (e.g. on labels or on the data).

The `Dataset` and its functions are included in the [API documentation](https://explabox.readthedocs.io/en/latest/api/explabox.digestibles.html) and are now part of the example usage guide. 

Examples include:
```python
dataset = box.explore.instances(split="test")  # get instances for split, "test" by default

dataset.head(n=10)  # get the first 10 instances
dataset.tail(n=5)  # get the last 5 instances
dataset.sample(n=1, seed=0)  # sample 1 instance
dataset[['drugsComTest.tsv_160', 'drugsComTest.tsv_184']]  # get samples by key
dataset[:10]  # get the first ten instances
dataset.filter('positive')  # filter on the positive label
dataset.filter(lambda data, label: len(data) < 100)  # get all instances with string length < 100
```

The functionality will be part of the next stable release of the `explabox`.
